target_x: 6.0
target_y: 0.0
target_z: 0.0

debug_mode: true

planner:
  uav_radius: 0.3
  safe_margin: 0.2
  max_speed: 1.0
  min_safe_dist: 0.3
  
  corridor_width: 1.2
  replan_cooldown: 1.5
  enable_corridor: true